name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
                  
    - name: Git Semantic Version              
      uses: PaulHatch/semantic-version@v4.0.3
      with: 
        #tag_prefix: "v"
        major_pattern: "mejor:"
        minor_pattern: "feet:"
        format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: version
        #change_path: "src/my-service"
        #namespace: my-service
        #short_tags: true
        #bump_each_commit: false        
    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run:  |
        echo "NUEVA VERSION: $NEW_VERSION !!!!!!"
        docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}        
    - name: Build Docker Image
      run: |
      #  docker build -t ddiazr2020/nest-graphql-dev:1.0.1 .
    - name: Push Docker Image
      run: |
      #  docker push ddiazr2020/nest-graphql-dev:1.0.1
    #- name: Build the Docker image
    # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
